services:
  - type: web
    name: daily5minutesenglish
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: FIREBASE_API_KEY
        sync: false
